### PR TITLE
Feature/namespaces

### PR DESCRIPTION
**Pull request by mambax7**
Work in progress. Don't merge yet, but check it out and let me know if you're interested in moving to namespaces, the same way as we did in TdmDownloads...

### CODE REVIEW

**Comment by ggoffy** [comment]
hi Michael, yes of course I want to move to namespaces. and I didn't go into detail hwo this works till now, therefore it would be great if you make this ;-)

**Comment by mambax7** [comment]
It seems to be working, but there could be some bugs, and some code that could be deleted. 
Check it out, and if you feel comfortable, merge it, and then we can look for bugs and further improvements. 
Your module, so it's your call...

**Comment by ggoffy** [comment]
FineimpuploadHandler from wggallery

**Comment by mambax7** [comment]
OK, let me check, and I'll get back to you...

**Comment by ggoffy** [comment]
hi
i made a step back and used my "old" class. Then I went through the code line by line with phpstorm and fixed several problem. Maybe now it is not "fully namespaced" but it works again

**Comment by mambax7** [comment]
Thanks! 
I'll check it out...

**Comment by ggoffy** [comment]
hi. thank you. please test always "multiupload of image" and "Edit album image" (with grid creation and image cropping), these functionaltities are the "core" and most sensitive ;-)

**Comment by mambax7** [comment]
Will do!!!

**Pull request merged**
