### PR TITLE
Feature/namespaces

### PR DESCRIPTION
**Pull request by mambax7**
Back to Namespaces.  Please don't merge yet, till you test it yourself. 
I have also added test data.  Install as fresh, and then import the Test data using the button in the Dashboard.

### CODE REVIEW

**Comment by ggoffy** [comment]
hi

multiupload was not working again. following changes I made to get it working again:
Class/Common/FineimpuploadHandler.php must be in Class-folder, subfolder Common will be not accepted
class name must be `class WggalleryFineImpUploadHandler extends \SystemFineUploadHandler`
`class FineimpuploadHandler extends \SystemFineUploadHandler` is not working

upload.php
changed line 122 from` 'handler' => '\XoopsModules\Wggallery\Common\FineimpuploadHandler',` into ` 'handler' => 'FineimpuploadHandler',`

FineimpuploadHandler.php
remove `namespace XoopsModules\Wggallery\Common;`

dont ask me for the reasons

**Comment by mambax7** [comment]
I tested here several times, and the multi-upload worked flawlessly. When did you download the XOOPS version that you're using? 
You need to have this one:
https://github.com/XOOPS/XoopsCore25/pull/618

**Comment by ggoffy** [comment]
2 hours ago

**Comment by ggoffy** [comment]
maybe it is again a problem of the server configuration.

in the past we changed in ajaxfineupload.php
`$claims = TokenReader::fromHeader('fineuploader', 'Authorization', $assert);`
into
`$claims = TokenReader::fromRequest('fineuploader', 'Authorization', $assert);`
because  fromHeader was not working

maybe Richard has an idea

**Comment by mambax7** [comment]
It worked perfectly on our Demo with the latest XOOPS version. I have imported the two sample albums, and then create a new one, and uploaded these images, and it worked flawlessly:
http://demo.xoops.org/modules/wggallery/images.php?op=list&alb_id=3&alb_pid=0

**Comment by mambax7** [comment]
Did you run /upgrade after you downloaded the files from XOOPS?

**Comment by ggoffy** [comment]
sorry, I think I didnt run upgrade. it works now. perfect ;-)

**Comment by mambax7** [comment]
Awesome!!!  I'm happy that it works now. 
I'm just trying to make those classes as generic as possible, so I can just copy files, change the namespace, and it's working.

**Comment by ggoffy** [comment]
do we need a copyright info for the test images?

**Comment by mambax7** [comment]
I checked again, and these images are Free for commercial use, No attribution required.
But in the spirit of OpenSource, I'll track the authors and give them credit.

**Pull request merged**
