### PR TITLE
notification fixes

### PR DESCRIPTION
**Pull request by mambax7**

### CODE REVIEW

**Comment by ggoffy** [comment]
Tahnk you. I will test it

**Comment by ggoffy** [comment]
what is also not clear for me is why i do not see this checkbox for select a notification option on index site with this code:
```
$modversion['notification']['category'][] = [
    'name' => 'albums',
    'title' => _MI_WGGALLERY_ALBUMS_NOTIFY,
    'description' => '',
    'subscribe_from' => ['index.php', 'albums.php'],
    'item_name' => 'alb_id',
    'allow_bookmark' => 1,
];
```
subscribe_fro includes index.php and it doesnt work

**Comment by mambax7** [comment]
I have to leave now, but I'll try to look into it later tonight or tomorrow morning...

**Comment by ihackcode** [comment]
> hi, thank you Michael
> 
> the reason why I replace
> `$notificationHandler->triggerEvent('global', 0, 'album_new');`
> by
> `$notificationHandler->triggerEvent('global', $newAlbId, 'album_new');`
> was, that I want the name and link to the new album (not: there is somewhere a new album)
> 
> at the moment I get
> grafik

For STORY_NAME AND STORY_URL you'll need to add $extra_tags

`$notification_handler->triggerEvent ($category, $item_id, $event, $extra_tags=array(), $user_list=array(), $module_id=null,         $omit_user_id=null);`

* $extra_tags - associative array of tags you wish to expand in your mail template.
https://xoops.org/modules/newbb/viewtopic.php?post_id=363974#363974

**Comment by mambax7** [comment]
Thanks @ihackcode! 
I just made a PR with these changes. 

Goffy,  reg. "why i do not see this checkbox for select a notification option on index site ", I believe that you can see only the 'global"  entries. 
You don't see the category itself, but only the events that belong to that category, like here in this link:
```php
modules/wggallery/images.php?op=list&ref=albums&alb_id=1&alb_pid=0
```

image

**Pull request merged**
